feat: implemented Book entity, BookRepository and BookService with sa…
PavloMelnyk10/spring-bookstore pull request #1
Opened 2024-11-17 03:25 UTC by PavloMelnyk10

…ve() and findAll() methods

2024-11-17 16:06 UTC, Elena-Bruyako requested changes
see comments

2024-11-17 16:06 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstore/SpringBookstoreApplication.java
> +            Book book1 = new Book(null, "Spring Boot Essentials", "John Smith",
don't use numbers for naming

2024-11-17 16:06 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstore/model/Book.java
> +@Data
Don't use `@Data` for entities
```suggestion
```

2024-11-17 16:06 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstore/model/Book.java
> +@NoArgsConstructor
Redundant annotations 
```suggestion
```

2024-11-17 16:06 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstore/model/Book.java
> +public class Book {
Add `@Table`

2024-11-17 16:06 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstore/repository/impl/BookRepositoryImpl.java
> +@Repository
```suggestion
@Repository
@RequiredArgsConstructor
```

2024-11-17 16:06 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstore/repository/impl/BookRepositoryImpl.java
> +    }
```suggestion
```

2024-11-17 16:06 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstore/repository/impl/BookRepositoryImpl.java
> +        try (Session session = sessionFactory.openSession()) {
don't use try with resources and transaction, session will be closed before catch block and rollback won't happened if exception will thrown

2024-11-17 16:06 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstore/repository/impl/BookRepositoryImpl.java
> +            throw new RuntimeException("Failed to add book: " + book, e);
```suggestion
            throw new DataProcessingException("Failed to add book: " + book, e);
```

2024-11-17 16:06 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstore/repository/impl/BookRepositoryImpl.java
> +            throw new RuntimeException("Can't get all books", e);
```suggestion
            throw new DataProcessingException("Can't get all books", e);
```

2024-11-17 16:06 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstore/repository/impl/BookRepositoryImpl.java
> +            CriteriaQuery<Book> criteriaQuery = session.getCriteriaBuilder()
There is no sense to use CriteriaBuilder

2024-11-17 16:06 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstore/service/impl/BookServiceImpl.java
> +@Service
```suggestion
@Service
@RequiredArgsConstructor
```

2024-11-17 16:06 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstore/service/impl/BookServiceImpl.java
> +    private BookRepository bookRepository;
```suggestion
    private final BookRepository bookRepository;
```

2024-11-19 12:43 UTC, Elena-Bruyako requested changes
see comments

2024-11-19 12:43 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstore/repository/impl/BookRepositoryImpl.java
> +    @Autowired
```suggestion
```

2024-11-19 12:43 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstore/service/impl/BookServiceImpl.java
> +@Service
add `@RequiredArgsConstructor`

2024-11-19 12:43 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstore/service/impl/BookServiceImpl.java
> +    private BookRepository bookRepository;
fix comment

2024-11-19 15:20 UTC, okuzan approved these changes

2024-11-19 15:20 UTC, okuzan commented on src/main/java/mate/academy/bookstore/repository/impl/BookRepositoryImpl.java
> +
```suggestion
```

2024-11-19 15:24 UTC, merged